In [ ]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [6]:
a=np.random.rand(2,3,4)
a
sum=a.sum()
sum

13.99397953429126

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [12]:
a=np.random.randint(0,10,size=(2,3,4,5))
a

array([[[[9, 2, 9, 3, 0],
         [1, 2, 2, 7, 3],
         [2, 5, 4, 8, 9],
         [8, 3, 2, 8, 3]],

        [[2, 6, 8, 9, 1],
         [5, 5, 2, 6, 9],
         [0, 7, 3, 0, 5],
         [6, 5, 5, 5, 6]],

        [[3, 7, 5, 8, 1],
         [5, 6, 8, 7, 4],
         [2, 6, 1, 2, 4],
         [5, 9, 5, 6, 6]]],


       [[[9, 1, 6, 3, 3],
         [2, 7, 4, 4, 9],
         [4, 4, 9, 5, 9],
         [2, 4, 7, 1, 0]],

        [[4, 0, 2, 3, 0],
         [5, 4, 2, 9, 4],
         [5, 9, 0, 6, 2],
         [3, 4, 9, 6, 3]],

        [[1, 8, 1, 3, 3],
         [9, 4, 2, 3, 9],
         [6, 2, 7, 1, 5],
         [3, 9, 3, 3, 4]]]])

# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [16]:
a=np.random.rand(2,3,4,5)
print(a)
#calculate mean
print("mean",a.mean(axis=1))

[[[[4.74753930e-01 3.28243522e-01 2.32882244e-02 5.68121388e-01
    2.77621479e-02]
   [8.87548312e-01 3.03218915e-01 3.76358507e-01 6.27970185e-01
    7.55134308e-01]
   [2.61180556e-01 9.29591768e-01 2.29831067e-01 3.93139742e-01
    1.58159181e-01]
   [5.42046733e-01 2.07429224e-01 3.03150217e-01 5.99770122e-01
    2.54151229e-01]]

  [[9.77958670e-01 9.50029466e-01 9.02737807e-02 8.66520895e-02
    9.61583259e-01]
   [1.05493979e-01 9.89369361e-01 7.98097447e-01 4.32953314e-01
    1.73234265e-01]
   [4.16648729e-01 2.25223629e-01 3.98502727e-01 7.50209661e-01
    4.24744385e-01]
   [5.87587967e-02 9.29467376e-02 2.38567538e-02 5.77464786e-01
    7.08463214e-01]]

  [[5.08076337e-01 9.80443185e-01 6.68667121e-01 3.40060350e-02
    2.30100494e-01]
   [6.90372898e-01 2.41845282e-01 6.69572898e-01 4.80027961e-04
    9.87374893e-01]
   [9.89923203e-01 5.95663241e-01 5.97753349e-02 8.91129599e-01
    7.79679472e-01]
   [7.50973954e-01 2.74922717e-01 6.70094353e-01 9.83749689e-01
    9.66

# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [26]:
a=np.random.rand(7,24,60)
a

b=a.mean(axis=(1,2))
b

array([0.50865295, 0.49715859, 0.50025614, 0.50337984, 0.50652579,
       0.51132591, 0.48926189])

Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [27]:
a=np.random.rand(4,7,24,60)
a

b=a.mean(axis=(2,3))
b

array([[0.49352816, 0.49730824, 0.50356409, 0.48344765, 0.5132326 ,
        0.49389137, 0.50025889],
       [0.50311712, 0.49436332, 0.49966599, 0.49054263, 0.49746335,
        0.49631803, 0.49049569],
       [0.49809048, 0.50980795, 0.50441371, 0.49858594, 0.49537717,
        0.49480888, 0.50007205],
       [0.49359175, 0.49066116, 0.50981521, 0.51676873, 0.49545956,
        0.49854243, 0.49212495]])

# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Inpumt:

In [28]:
dimensions = np.random.rand(100, 50, 3)

# Calculate average for each dimension across all objects
average_length = np.mean(dimensions[:, :, 0])
average_width = np.mean(dimensions[:, :, 1])
average_height = np.mean(dimensions[:, :, 2])

print(f"Average Length: {average_length:.2f}")
print(f"Average Width: {average_width:.2f}")
print(f"Average Height: {average_height:.2f}")


Average Length: 0.50
Average Width: 0.50
Average Height: 0.50


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [29]:
array=np.random.rand(5,6,7)
array

array([[[0.63039933, 0.93706201, 0.75936182, 0.384415  , 0.36831413,
         0.43975651, 0.85203607],
        [0.69407561, 0.35445133, 0.58830814, 0.92002703, 0.47542917,
         0.47083218, 0.16726163],
        [0.96315543, 0.03379069, 0.50952371, 0.04687357, 0.10079677,
         0.70487797, 0.60786186],
        [0.12804574, 0.43078644, 0.52087025, 0.09662167, 0.00114842,
         0.15577438, 0.24348611],
        [0.70353265, 0.67688438, 0.47654514, 0.90835163, 0.99478776,
         0.55035291, 0.45611317],
        [0.00734708, 0.60173793, 0.81839184, 0.48533799, 0.13449264,
         0.87792   , 0.34227496]],

       [[0.56195002, 0.71387233, 0.28074182, 0.55943039, 0.63106477,
         0.54614938, 0.04825982],
        [0.50021484, 0.6022633 , 0.98288553, 0.86504171, 0.86832724,
         0.01650928, 0.45166839],
        [0.3948194 , 0.34091775, 0.01012554, 0.50341731, 0.41387187,
         0.64327752, 0.04465294],
        [0.14560046, 0.83343912, 0.65588808, 0.86517583, 0.62360282,
  

In [38]:
#Total number of measurements
print(array.size)

#Average measurement value
print(array.mean(axis=(1,2)))

#Standard deviation of measurements
print(array.std(axis=(1,2)))

#Minimum measurement value
print(array.min(axis=(1,2)))

#Maximum measurement value
print(array.max(axis=(1,2)))

210
[0.49093841 0.48049799 0.53139047 0.42040154 0.52563395]
[0.28950963 0.27221941 0.28876892 0.27130681 0.28355889]
[0.00114842 0.00760815 0.02092094 0.00178567 0.020697  ]
[0.99478776 0.98288553 0.99932028 0.98056942 0.97444915]
