# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [ ]:
import numpy as np
#Prepend ones to smaller array's shape.
a=np.array([1,2,3])
b=np.array([[4],[5],[6]])
print("part1:",a+b)

#Dimension of size 1 are repeated without copying
a=np.array([[1]])
b=np.array([4,5,6])
print("part2:",a*b)

part1: [[5 6 7]
 [6 7 8]
 [7 8 9]]
part2: [[4 5 6]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [ ]:
#Using reduce() operation on an array
a=np.array([[1,2,3],[4,5,6]])
print(np.add.reduce(a))
print(np.add.reduce(a,axis=0))
print(np.add.reduce(a,axis=1))

#Using accumulate()
a=np.array([1,2,3,4])
print(np.add.accumulate(a))
a=np.array([[1,2,3],[4,5,6]])
print(np.add.accumulate(a))

[5 7 9]
[5 7 9]
[ 6 15]
[ 1  3  6 10]
[[1 2 3]
 [5 7 9]]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [22]:
first_row=np.arange(10,80,5)
print("first_row", first_row)
second_row=np.arange(5,47,3)
print("second_row", second_row)
combined_array=np.array((first_row,second_row))
print("combined_array", combined_array)

first_row [10 15 20 25 30 35 40 45 50 55 60 65 70 75]
second_row [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]
combined_array [[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44]]


### Now use indexing to select the 5th 7th and 11th columns

In [23]:
selected_columns=combined_array[:,[4,6,10]]
print(selected_columns)

[[30 40 60]
 [17 23 35]]


### Select the 2nd row and fourth-last to second-last columns

In [24]:
selected_row=combined_array[1,-4:-1]
print(selected_row)

[35 38 41]


### Select 3rd to 3rd last columns skipping every second column

In [25]:
selected_columns1=combined_array[:,2:-2:2]
print(selected_columns1)

[[20 30 40 50 60]
 [11 17 23 29 35]]


###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [39]:
# prompt: Select 3rd to 3rd last columns skipping every second column but in reverse order

selected_columns_reverse = combined_array[:,2:-2:2][:,::-1]
print(selected_columns_reverse)


[[60 50 40 30 20]
 [35 29 23 17 11]]


### We will work with the following array:

In [ ]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Use slicing only to select 3rd and last row along with 2nd and last columns

In [44]:
sliced_array=a[[2,-1],[1,-1]]
print(sliced_array)

[11 24]


### Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [48]:
# Define the larger array
larger_array = [
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7],
    [8, 9],
    [10, 11],
    [12, 13],
    [14, 15],
    [16, 17],
    [18, 19],
    [20, 21],
    [22, 23]
]

# Extract the sub-array [[2, 3], [12, 13], [22, 23]]
sub_array = [
    larger_array[1],
    larger_array[6],
    larger_array[11]
]

print(sub_array)

[[2, 3], [12, 13], [22, 23]]


### Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [50]:
arr = np.arange(24).reshape(4, 6)
print(arr)

# Extract sub-array using fancy indexing and slicing
sub_array = arr[[1, 2, 3], 1::2]  # Rows 1, 2, and 3 (inclusive), columns with step 2

print(sub_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 7  9 11]
 [13 15 17]
 [19 21 23]]


### Change the values 1, 10, 19 and 22 in the array to -2

In [52]:
a = np.arange(25).reshape(5, 5)

a[[0, 2, 3, 4], [1, 0, 3, 2]] = -2

print(a)


[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 -2 19]
 [20 21 -2 23 24]]


### Repeat above using boolean indexing

In [53]:
# Create a boolean mask
mask = (a == 1) | (a == 10) | (a == 19) | (a == 22)

a[mask] = -2

print(a)


[[ 0 -2  2  3  4]
 [ 5  6  7  8  9]
 [-2 11 12 13 14]
 [15 16 17 -2 -2]
 [20 21 -2 23 24]]


### Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [54]:
arr = np.arange(24).reshape(4, 6)

# Define the boolean mask for row selection
row_mask = np.array([0, 1, 2])

# Extract the sub-array using slicing and boolean indexing
sub_array = arr[row_mask, 0::3]

# Print the sub-array
print(sub_array)


[[ 0  3]
 [ 6  9]
 [12 15]]


### Calculating the sum, min and max of all diagonal values

In [55]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the sum of all diagonal values
diagonal_sum = np.trace(a)

# Calculate the minimum of all diagonal values
diagonal_min = np.min(np.diagonal(a))

# Calculate the maximum of all diagonal values
diagonal_max = np.max(np.diagonal(a))

# Print the results
print("Sum of diagonal values:", diagonal_sum)
print("Minimum diagonal value:", diagonal_min)
print("Maximum diagonal value:", diagonal_max)


Sum of diagonal values: 15
Minimum diagonal value: 1
Maximum diagonal value: 9


### Calculate the sum of differences between the 2nd row and 2nd last column

In [56]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calculate the difference between the 2nd row and 2nd last column
difference = a[1, :] - a[-2, :]

# Calculate the sum of the differences
sum_of_differences = np.sum(difference)

# Print the result
print("Sum of differences:", sum_of_differences)


Sum of differences: 0


### Create a new array that is the sum of even rows and odd rows

In [58]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Find the sum of even rows
even_rows_sum = np.sum(a[::2], axis=1)

# Find the sum of odd rows
odd_rows_sum = np.sum(a[1::2], axis=1)

# Create a new array that is the sum of even and odd rows
new_array = even_rows_sum + odd_rows_sum

# Print the new array
print(new_array)


[21 57]


## You are done. Good job!