In [ ]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Q.1
**Statement:** You are working with a retail store that needs to manage its inventory efficiently. They have provided you with a dataset containing information about products, their quantities in stock, and the number of units sold daily for the past week. Total number of products are 5. Your task is to calculate the following:



1.The total sales for each product over the past week.

2.The average daily sales for each product.

3.The product with the highest sales.

4.The product with the lowest sales.

5.The total sales for all products combined.

You are required to use NumPy for efficient data processing and calculations. Write code to solve this inventory management problem.

In [30]:
import numpy as np

# Sample data (replace with your actual data)
product_names = np.array(['Product A', 'Product B', 'Product C', 'Product D', 'Product E'])
quantities_in_stock = np.array([100, 150, 200, 250, 50])

daily_sales_data = np.array([[10, 15, 20, 25, 30, 35, 40],
                             [5, 7, 8, 10, 12, 14, 16],
                             [15, 20, 25, 30, 35, 40, 40],
                             [12, 25, 20, 40, 20, 32, 55],
                             [15, 20, 25, 30, 35, 40, 45]])

# Calculate total sales revenue for each product over the past week
total_sales_per_product = np.sum(daily_sales_data, axis=1)
print("Total Sales per Product:", total_sales_per_product)

# Calculate average daily sales for each product
daily_sales_per_product = daily_sales_data.mean(axis=1)
print("Average Daily Sales per Product:", daily_sales_per_product)


# Find the product with the highest and lowest sales
highest_sales_product = product_names[total_sales_per_product.argmax()]
print("Highest sales product", highest_sales_product)

lowest_sales_product = product_names[total_sales_per_product.argmin()]
print("Lowest sales product", lowest_sales_product)

# Calculate the total sales revenue for all products combined
total_sales_revenue = total_sales_per_product.sum()
print("total_sales_revenue",total_sales_revenue)

Total Sales per Product: [175  72 205 204 210]
Average Daily Sales per Product: [25.         10.28571429 29.28571429 29.14285714 30.        ]
Highest sales product Product E
Lowest sales product Product B
total_sales_revenue 866


# Q.2
**Statement:** Statement: You are working with a manufacturing plant that produces various components. They have provided you with data on the production rates of five different machines over the past month. Your task is to analyze the performance of these machines by calculating the following metrics:

1.The total production output for each machine over the past month.

2.The average daily production rate for each machine.

3.The machine with the highest total production output.

4.The machine with the lowest total production output.

The overall production efficiency of the plant, which is defined as the ratio of the total production output to the total number of hours worked, and working hour for each day is 2 hours.

In [33]:


# Sample data (replace with your actual data)
machine_names = np.array(['Machine A', 'Machine B', 'Machine C', 'Machine D', 'Machine E'])
print("machine_names",machine_names)
production_rates = np.random.randint(100, 201, size=(5, 30))  # 5 machines, 30 days
production_rates

# Generate random production rates between 100 and 200 for 5 machines and 30 days
production_rates = np.random.randint(100, 201, size=(5, 30))  # 5 machines, 30 days
production_rates

# Calculate total production output for each machine over the past month
total_production_per_machine = np.sum(production_rates, axis=1)
print("Total Production per Machine:", total_production_per_machine)

# Calculate average daily production rate for each machine
average_daily_production = np.mean(production_rates, axis=1)
print("Average Daily Production per Machine:", average_daily_production)

# Find the machine with the highest and lowest total production output
highest_total_production = machine_names[total_production_per_machine.argmax()]
print("Machine with Highest Total Production:", highest_total_production)
lowest_total_production = machine_names[total_production_per_machine.argmin()]
print("Machine with Lowest Total Production:", lowest_total_production)

# Calculate the overall production efficiency of the plant
overall_production_efficiency = np.sum(total_production_per_machine) / (2 * 30) #(2*30) represents the 2hours/day * 30 days
print("Overall Production Efficiency:", overall_production_efficiency)


machine_names ['Machine A' 'Machine B' 'Machine C' 'Machine D' 'Machine E']
Total Production per Machine: [4530 4221 4396 4498 4480]
Average Daily Production per Machine: [151.         140.7        146.53333333 149.93333333 149.33333333]
Machine with Highest Total Production: Machine A
Machine with Lowest Total Production: Machine B
Overall Production Efficiency: 368.75


# Q3:

**Statment**
You are working on a project that involves simulating sensor data for a network of 10 sensors over a period of 15 days. Each sensor collects data once per hour. Your task is to generate a NumPy array named sensor_data to represent this simulated sensor data and perform following statistical analysis on it.

Populate the sensor_data array with random floating-point values between 0.0 and 100.0
The generated values should represent sensor readings collected once per hour.

After generating the sensor_data array, perform the following statistical **calculations:**

1.Calculate the mean (average) sensor reading for each sensor over the 15 days.

2.Calculate the standard deviation of sensor readings for each sensor.

3.Calculate the maximum sensor reading for each sensor.

4.Calculate the minimum sensor reading for each sensor.

5.Calculate the overall mean sensor reading for all sensors and all days.

6.Calculate the overall standard deviation of sensor readings for all sensors an

In [42]:
import numpy as np

# Data Generation Requirements
num_sensors = 10
num_days = 15
hours_per_day = 24
shape = (num_sensors, num_days * hours_per_day)
print("shape",shape)

# Populate the sensor_data array with random floating-point values between 0.0 and 100.0
sensor_data = np.random.uniform(0.0, 100.0, shape)
print("sensor_data",sensor_data)

#Calculate the mean (average) sensor reading for each sensor over the 15 days.
mean_sensor_reading = np.mean(sensor_data, axis=1)
print("mean_sensor_reading",mean_sensor_reading)

#Calculate the standard deviation of sensor readings for each sensor.
std_sensor_reading = np.std(sensor_data, axis=1)
print("std_sensor_reading",std_sensor_reading)

#Calculate the maximum sensor reading for each sensor.
max_sensor_reading = np.max(sensor_data, axis=1)
print("max_sensor_reading",max_sensor_reading)

#Calculate the minimum sensor reading for each sensor.
min_sensor_reading = np.min(sensor_data, axis=1)
print("min_sensor_reading",min_sensor_reading)

#Calculate the overall mean sensor reading for all sensors and all days.
overall_mean_sensor_reading = np.mean(sensor_data)
print("overall_mean_sensor_reading",overall_mean_sensor_reading)

#Calculate the overall standard deviation of sensor readings for all sensors
overall_std_sensor_reading = np.std(sensor_data)
print("overall_std_sensor_reading",overall_std_sensor_reading)

shape (10, 360)
sensor_data [[55.63786044 61.08105506 41.38538962 ...  2.23741038 43.71354589
  71.86178434]
 [17.81513454 44.61088503 18.80713827 ... 48.6078432  65.88879419
  29.54322666]
 [29.62598438 16.46447704  5.09961774 ... 11.26094332 76.02817129
   4.62487305]
 ...
 [99.20080193 14.60639501 25.2675193  ... 46.99364432 71.16919909
   7.6261114 ]
 [17.54573038 41.71705074 79.38885772 ... 80.43796756 69.8047513
   7.59967691]
 [43.25647624  3.33988888 47.31889989 ...  3.52270259 24.07327452
  73.01873083]]
mean_sensor_reading [48.8798619  50.87963183 48.23347266 51.05486453 49.51344681 50.31099175
 50.16522603 51.48883426 49.48017649 50.99033728]
std_sensor_reading [29.16667167 30.13610803 28.49161312 28.94961173 30.01097426 28.20823711
 28.80326173 28.48948331 28.26937764 28.12729959]
max_sensor_reading [99.8279335  99.88823846 99.96565195 99.64809715 99.54125207 99.80669179
 99.82411465 99.91569897 99.99772795 99.70217757]
min_sensor_reading [0.12291802 0.10421541 0.34823748 0

# Q4:

**Statement**: You are tasked with analyzing the exam scores of 30 students in a class over a period of 10 exams. The exam scores are represented as a NumPy, where each row corresponds to a different student, and each column represents their score in a specific exam.

Populate the exam_scores array with random integer values between 50 and 100 to simulate students' exam performance.

After generating the exam_scores array, perform the following tasks:

1.Calculate the average score for each student over the 10 exams.

2.Calculate the standard deviation of scores for each student.

3.Identify students who have consistently performed well, defined as those whose average score is above 85.

4.Identify students who may need additional support, defined as those whose average score is below 50.

Write code to create and populate the exam_scores array and then perform the specified statistical analysis and performance evaluation tasks on the data.





In [61]:
import numpy as np

# Create the exam_scores array (30 students, 10 exams)
num_students = 30
num_exams = 10

# Populate the exam_scores array with random scores between 50 and 100
exam_scores = np.random.randint(50, 101, size=(num_students, num_exams))
print("exam_scores",exam_scores)

# 1. Calculate the average score for each student over the 10 exams
average_scores = np.mean(exam_scores, axis=1)
print("average_scores",average_scores)

# 2. Calculate the standard deviation of scores for each student
std_scores = np.std(exam_scores, axis=1)
print("std_scores",std_scores)

# 3. Identify students who have consistently performed well (average score > 85)
consistent_students = np.where(average_scores > 85)[0]
print("consistent_students",consistent_students)
for i in consistent_students:
  print(f"Student {i+1} has consistently performed well.")

# 4. Identify students who may need additional support (average score < 60)
additional_support_students = np.where(average_scores < 60)[0]
print("additional_support_students",additional_support_students)
for i in additional_support_students:
  print(f"Student {i+1} may need additional support.")


exam_scores [[ 72  57  52  79  82  72  93  70  96  84]
 [ 98  92  60  55  64  64  97  73  64  80]
 [ 56  53  60  56  53  91  62  99  84  72]
 [ 55  56  90  84  57  94  62  55  82  85]
 [ 85  55  88  72  51  61  88  55  74  75]
 [ 93  56  72  84  57  77  86  65  69  97]
 [ 51  79  79  99  90  63  75  66  50  87]
 [ 80  88  54  54 100  84  94  99  54  58]
 [ 54  96  56  85  99  79  81  89  79  97]
 [ 75  69  68  85  76  54  52  55  68  73]
 [ 59  63  68  63  67  56  98  89  68 100]
 [ 93  85  73  72  92  78  70  93  75  69]
 [ 94  78  64  92  73  94  85  63  59  78]
 [ 66  96  80  88  80  70  65  89  93  70]
 [ 69  79  71  95  88  53  71  69  66  79]
 [ 64  52  87  87  87  97  51  80 100  99]
 [ 68  71  69  51  54  88  95  60  65  63]
 [ 68  63  96  50  51  75  82  62  74  78]
 [ 88  70  55  99  74  95  52  62  84  85]
 [ 79  66  81  55  97 100  95  83  53  66]
 [ 66  99  91  96  75  79  81  85  98  53]
 [ 93  50  76  52 100  78  64  95  66  51]
 [ 75  99  90  96  96  99  59  63  50  51]