In [2]:
#import the required libraries
import numpy as np

# Step 1 : Read the Data!

In [4]:
#give path of the source-file and store that path in a variable named census
census = "makeSenseOfCensus.csv"

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [250]:
data = np.genfromtxt(census , delimiter = "," , skip_header = 1 )
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [80]:
#print the type of data
data.dtype

dtype('float64')

# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [34]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [ ]:
append = np.concatenate((data , new_record), axis = 0)

In [36]:
#display after appending the new record at the end of the array.
append

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [54]:
age = data[:,0]
print (age)

[39. 50. 38. 53. 28. 37. 49. 52. 31. 42. 37. 30. 23. 32. 40. 34. 25. 32.
 38. 43. 40. 54. 35. 43. 59. 56. 19. 54. 39. 49. 23. 20. 45. 30. 22. 48.
 21. 19. 31. 48. 31. 53. 24. 49. 25. 57. 53. 44. 41. 29. 25. 18. 47. 50.
 47. 43. 46. 35. 41. 30. 30. 32. 48. 42. 29. 36. 28. 53. 49. 25. 19. 31.
 29. 23. 79. 27. 40. 67. 18. 31. 18. 52. 46. 59. 44. 53. 49. 33. 30. 43.
 57. 37. 28. 30. 34. 29. 48. 37. 48. 32. 76. 44. 47. 20. 29. 32. 17. 30.
 31. 42. 24. 38. 56. 28. 36. 53. 56. 49. 55. 22. 21. 40. 30. 29. 19. 47.
 20. 31. 35. 39. 28. 24. 38. 37. 46. 38. 43. 27. 20. 49. 61. 27. 19. 45.
 70. 31. 22. 36. 64. 43. 47. 34. 33. 21. 52. 48. 23. 71. 29. 42. 68. 25.
 44. 28. 45. 36. 39. 46. 18. 66. 27. 28. 51. 27. 28. 27. 21. 34. 18. 33.
 44. 43. 30. 40. 37. 34. 41. 53. 31. 58. 38. 24. 41. 47. 41. 23. 36. 40.
 35. 24. 26. 19. 51. 42. 37. 18. 36. 35. 58. 17. 44. 37. 35. 60. 54. 37.
 50. 38. 45. 25. 31. 64. 90. 54. 53. 18. 60. 66. 75. 65. 35. 41. 25. 33.
 28. 59. 40. 41. 38. 23. 40. 41. 24. 20. 38. 56. 58

Find the max age and store it in a variable called 'max_age'.



In [64]:
#print the max_age
max_age= age.max()
max_age

90.0

Find the min age and store it in a variable called 'min_age'.

In [66]:
#print the min_age
min_age = age.min()
min_age

17.0

Find the mean of the age and store it in a variable called 'age_mean'.

In [68]:
#print the age_mean
age_mean = age.mean()
age_mean

38.051

Find the standard deviation of the age and store it in a variable called 'age_std'

In [72]:
#print the age_std
age_std = age.std()
age_std

13.342803266180612

# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [92]:
Race_column = data[:, 2]

In [264]:
race_0 = data[Race_column == 0]
print(race_0)

race_1 = data[Race_column == 1]

race_2 = data[Race_column == 2]

race_3 = data[Race_column == 3]

race_4 = data[Race_column == 4]
print(race_4)

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]
[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [106]:
#len_0
len_0 = len(race_0)
len_0

10

In [108]:
#len_1
len_1 = len(race_1)
len_1

27

In [110]:
#len_2
len_2 = len(race_2)
len_2

110

In [112]:
#len_3
len_3 = len(race_3)
len_3

6

In [114]:
#len_4
len_4 = len(race_4)
len_4

847

Find out which is the race with the minimum no. of citizens

In [156]:
#Find out which is the race with the maximum no. of citizens

max_race = np.argmax([len_0 , len_1 , len_2 , len_3 , len_4])

print ("race with the maximum no. of citizens:", max_race)

race with the maximum no. of citizens: 4


Find out which is the race with the minimum no. of citizens

In [144]:
min_race = np.argmin([len_0 , len_1 , len_2 , len_3 , len_4])

print ("race with the minimum no. of citizens:", min_race)

race with the minimum no. of citizens: 3


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [152]:
minority_race = min_race
print("index of the race having the least no. of citizens:", minority_race)

index of the race having the least no. of citizens: 3


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [158]:
#maximum
majority_race = max_race
print("index of the race having the maximum no. of citizens:", majority_race)

index of the race having the maximum no. of citizens: 4


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [224]:
#from age column, filter out age data > 60
age = data[:,0]
senior_citizen = data[age>60]
print(senior_citizen)

[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [226]:
working_hours = senior_citizen[:,6]

working_hours_sum = np.sum(working_hours)

print(working_hours_sum)

1917.0


c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [228]:
senior_citizens_len = len(senior_citizen)

print(senior_citizens_len)

61


d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [236]:
avg_working_hours = working_hours_sum / senior_citizens_len

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [238]:
print(avg_working_hours)

31.42622950819672


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [242]:
education_num = data[:, 1]

print("education_num", education_num)

high = data[education_num > 10 ]

print("high", high)

low = data[education_num <= 10]

print("low", low)

education_num [13. 13.  9.  7. 13. 14.  5.  9. 14. 13. 10. 13. 13. 12. 11.  4.  9.  9.
  7. 14. 16.  9.  5.  7.  9. 13.  9. 10.  9.  9. 12. 10. 13. 10. 10.  7.
 10.  9. 10. 12.  5. 13. 13.  9.  9. 13.  9. 14. 11. 11. 10.  9. 15. 13.
  9. 10.  3. 11.  9.  9. 13.  4.  9. 16. 10.  9. 10.  9. 10. 10. 10. 13.
 13. 10. 10.  9. 12.  6.  7.  4.  9. 13.  9.  9.  9.  9.  9. 14.  5. 16.
 11. 10. 10.  9. 13. 10. 16. 10. 12.  9. 14. 13. 14. 10.  9.  9.  6.  7.
  9.  9. 13. 15.  9. 10.  9.  5. 10. 11. 10.  9. 10. 13. 13. 13. 10. 13.
 10. 12.  9. 10. 12.  9.  9. 13. 12. 14.  9. 11. 10. 10.  9. 10. 10. 11.
 10.  9. 10.  9.  7. 10. 10.  9. 13.  9.  9.  9. 13. 10.  9. 13.  2.  9.
 14.  9. 14. 10. 12. 14.  7. 11.  9.  9. 10. 13. 13.  9.  9.  9.  9. 13.
 10. 10. 10.  4. 10.  9. 13. 13. 14. 16. 10. 10. 13. 10. 13.  3. 10. 14.
 14.  9. 14.  9. 13. 10.  9.  7. 13.  9.  9.  7.  9.  9. 10.  9.  4. 13.
 12. 13. 13.  6. 10.  2.  9.  9.  1.  9.  6.  9. 11.  9.  7.  9. 10. 10.
 15.  9. 10. 13. 14.  9. 13.  9. 12. 

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [254]:
income_column = high[:, 7]
avg_pay_high = np.mean(income_column)

print("avg pay for high educated people is:", avg_pay_high)

avg pay for high educated people is: 0.42813455657492355


In [256]:
income_column = low[:, 7]
avg_pay_low = np.mean(income_column)

print("avg pay for low educated people is:", avg_pay_low)

avg pay for low educated people is: 0.13670133729569092
