In [ ]:
import numpy as np

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [ ]:
List1 = [1,2,3,4,5]
print(List1)

[1, 2, 3, 4, 5]


# Type
Accuire type of list in python.

In [ ]:
type(List1)

list

# Creatation of Arrays
1.Simple array creation

2.Checking array "TYPE"

3.Numeric "TYPE" of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [ ]:
arr=np.array([0,1,2,3,4])
print("Array:",arr)
print("Type of Array:",arr.dtype)
print("Type of Array:",type(arr))
print("Dimension of Array:",arr.ndim)
print("Shape of Array:",arr.shape)
print("Bytes per element",arr.itemsize)
print("Total bytes in an Array",arr.nbytes)

Array: [0 1 2 3 4]
Type of Array: int64
Type of Array: <class 'numpy.ndarray'>
Dimension of Array: 1
Shape of Array: (5,)
Bytes per element 8
Total bytes in an Array 40


In [ ]:
arr=np.array([0.1,1.2,2.3,3.2,4.5])
print("Array:",arr)
print("Type of Array:",arr.dtype)
print("Type of Array:",type(arr))
print("Dimension of Array:",arr.ndim)
print("Shape of Array:",arr.shape)
print("Bytes per element",arr.itemsize)
print("Total bytes in an Array",arr.nbytes)

Array: [0.1 1.2 2.3 3.2 4.5]
Type of Array: float64
Type of Array: <class 'numpy.ndarray'>
Dimension of Array: 1
Shape of Array: (5,)
Bytes per element 8
Total bytes in an Array 40


9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [ ]:
arr=np.array([0,1,2,3,4])
arr[2]=6.78
print(arr)

arr.fill(6.78)
print(arr)

[0 1 6 3 4]
[6 6 6 6 6]


11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [10]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print("Add two Arrays,",a+b)
print("Multiply two Arrays:",a*b)
print("Sqr of an Array:",a**b)

#Creating an Array
arr1=np.arange(0.0,11.0)
print("create an array",arr1)

#Multiply entire array with a scalar value
c = (2.0 * np.pi)
arr2=c*arr1
print("multiply entire array",arr2)

#Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0
arr3=np.arange(1.0,3.0,0.5)
print("Create an Array with 0.5 step",arr3)



Add two Arrays, [ 2  4  6  8 10]
Multiply two Arrays: [ 1  4  9 16 25]
Sqr of an Array: [   1    4   27  256 3125]
create an array [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
multiply entire array [ 0.          6.28318531 12.56637061 18.84955592 25.13274123 31.41592654
 37.69911184 43.98229715 50.26548246 56.54866776 62.83185307]
Create an Array with 0.5 step [1.  1.5 2.  2.5]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [8]:
import numpy as np

# Extract array indices from 1 to 3:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array Extraction",arr[1:3])

# Use negative indices as well
print("Negative Indices",arr[-9:-7])

# Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
print("Omitted Boundaries")
print(arr[:3])
print(arr[3:])
print(arr[-3:])

# Grab first three elements
print("1st 3 elements",arr[:3])

# Grab last two elements
print("last 2 elements",arr[-2:])

# Grab every other element
print("Grab other elements",arr[::2])

# slicing the last two elements returns the data there
print("Slice the last two elements",arr[-2:])

#Can we insert an iterable of length two? or a scalar value
print("Yes,we can insert an iterable of length two or a scalar value into various data structures like lists, tuples, dictionaries, and sets."
      "but the list are mutable ordered sequence can accept both iterables of length two and scalar values as elements.")
#For example:

#creat a list with 2 values
my_list=[1,2]
#insert an iterable of length two
my_list.insert(1, [3, 4])
print(my_list)

#insert a scalar value
my_list.insert(2, 5)
print(my_list)


# Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
# For example create a slice containing two elements of a changing b changed a! Have an experiment

#Creating a new array
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_list = a[3:5]
print("sliced list",sliced_list)

#change value in sliced list
sliced_list[0] = 100
print("sliced list after change in index",sliced_list)
print("after change in index",a)

# if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
a = np.array([[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]])
#print extracted rows
print("extract_rows",a[:2])
#print extracted columns values from row 3
print("extract_cols",a[:,[0,2,4]])

# Perform some masking on a = np.arange(0,36).reshape(6,6)
# with mask = np.array([1, 0, 1, 0, 0, 1])
mask = np.array([1, 0, 1, 0, 0, 1])
a = np.arange(0,36).reshape(6,6)
print("mask array",a[mask, :])


Array Extraction [1 2]
Negative Indices [1 2]
Omitted Boundaries
[0 1 2]
[3 4 5 6 7 8 9]
[7 8 9]
1st 3 elements [0 1 2]
last 2 elements [8 9]
Grab other elements [0 2 4 6 8]
Slice the last two elements [8 9]
Yes,we can insert an iterable of length two or a scalar value into various data structures like lists, tuples, dictionaries, and sets.but the list are mutable ordered sequence can accept both iterables of length two and scalar values as elements.
[1, [3, 4], 2]
[1, [3, 4], 5, 2]
sliced list [3 4]
sliced list after change in index [100   4]
after change in index [  0   1   2 100   4   5   6   7   8   9]
extract_rows [[0 1 2 3 4]
 [1 2 3 4 5]]
extract_cols [[0 2 4]
 [1 3 5]]
mask array [[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here

In [ ]:
#For loop to add corresponding elements in two lists

# Answer Here